repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
      
 # Flake8 includes pyflakes, pycodestyle, mccabe, pydocstyle, bandit
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bandit
          - flake8-blind-except
          - flake8-docstrings
          - flake8-logging-format
          - flake8-print