version: '3.7'

services:
  web:
    image: "fission_django_template:dev"

    build:
        target: development_build
        context: .
        args:
          DJANGO_ENV: development
        cache_from:
          - "fission_django_template:dev"
          - "fission_django_template:latest"
          - "*"
    command: python -Wd manage.py runserver 0.0.0.0:8000
    ports:
        - 8000:8000
    env_file:
        - ./.env.dev
    depends_on:
        - db
  sonarqube:
      image: sonarqube
      container_name: fission-django-template-sonarqube
      expose:
      - 9000
      ports:
      - "127.0.0.1:9000:9000"
      volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  
  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./.env.dev
  

volumes:
  postgres_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins: